import { ArrowRight, Menu, X } from "lucide-react";
import { useState } from "react";

export function SiteFrame({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const links = [["About", "/about"], ["Care & courses", "/care"], ["Learning hub", "/learn"], ["Blog", "/blog"], ["FAQ", "/faq"], ["Stories", "/stories"], ["News", "/news"], ["Contact", "/contact"]];
  return <div className="min-h-screen bg-[#f7fbfa] text-[#1a2a26]"><div className="bg-[#1a2a26] px-4 py-2 text-center text-[11px] font-semibold uppercase tracking-[0.18em] text-[#d8eee9]">Care should travel further than geography</div><header className="sticky top-0 z-40 border-b border-[#d9e9e5]/80 bg-[#f7fbfa]/95 backdrop-blur-xl"><div className="container flex h-[78px] items-center justify-between gap-6"><a href="/" className="flex items-center gap-3"><img src="/manus-storage/kindstepcare-logo_917bbc57.jpeg" alt="KindStepCare" className="h-11 w-11 rounded-xl object-cover" /><div className="leading-none"><div className="font-serif text-[19px] font-bold tracking-[-0.04em]">Kind<span className="text-[#ec900d]">Step</span>Care</div><div className="mt-1 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#0d7a6b]">Connecting care. Enabling progress.</div></div></a><nav className="hidden items-center gap-7 text-sm font-semibold text-[#3e5c56] lg:flex">{links.map(([label, href]) => <a key={href} href={href} className="transition hover:text-[#0d7a6b]">{label}</a>)}</nav><div className="flex items-center gap-3"><a href="/contact" className="hidden rounded-full bg-[#0d7a6b] px-5 py-3 text-sm font-bold text-white shadow-[0_10px_24px_rgba(13,122,107,0.18)] transition hover:-translate-y-0.5 sm:inline-flex">Start a conversation <ArrowRight className="ml-2 h-4 w-4" /></a><button aria-label="Toggle menu" className="rounded-full p-2 lg:hidden" onClick={() => setOpen((value) => !value)}>{open ? <X /> : <Menu />}</button></div></div>{open && <nav className="container grid gap-3 border-t border-[#d9e9e5] py-4 text-sm font-semibold lg:hidden">{links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}</nav>}</header>{children}<footer className="bg-[#1a2a26] py-14 text-[#c3ded8]"><div className="container grid gap-10 md:grid-cols-[1.2fr_.8fr_.8fr]"><div><div className="font-serif text-3xl font-semibold text-white">Kind<span className="text-[#f0a12b]">Step</span>Care</div><p className="mt-4 max-w-sm leading-7">Practical therapy, caregiver learning, and a kinder bridge to care for families across Kenya.</p></div><div><div className="eyebrow text-[#f5a623]">Explore</div><div className="mt-4 grid gap-3 text-sm font-semibold">{links.slice(0, 6).map(([label, href]) => <a key={href} href={href} className="hover:text-white">{label}</a>)}</div></div><div><div className="eyebrow text-[#f5a623]">Stay close</div><p className="mt-4 text-sm leading-6">Read a new learning note, field update, or carefully sourced cerebral palsy story.</p><a href="/contact" className="mt-5 inline-flex items-center text-sm font-bold text-white">Join the circle <ArrowRight className="ml-2 h-4 w-4" /></a></div></div></footer></div>;
}

export function PageHero({ eyebrow, title, copy, image = "/manus-storage/community-rehab_b091e960.jpg" }: { eyebrow: string; title: string; copy: string; image?: string }) { return <section className="reveal-up overflow-hidden bg-[#1a2a26] text-white"><div className="container grid items-end gap-12 py-20 lg:grid-cols-[1fr_.8fr] lg:py-28"><div><div className="eyebrow text-[#f5a623]">{eyebrow}</div><h1 className="mt-5 max-w-4xl font-serif text-5xl font-semibold leading-[.98] tracking-[-.05em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#c3ded8]">{copy}</p></div><div className="relative overflow-hidden rounded-[2rem] border border-[#f0a12b]/30"><img src={image} alt="Community-centered cerebral palsy support in Kenya" className="float-slow aspect-[4/3] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1a2a26]/50 to-transparent" /></div></div></section>; }
